### ISSUE TITLE
Testing Registrator server locally results in 400 errors

### ISSUE THREAD

**Issue by BenJWard** [JuliaComputing/Registrator.jl#60]
I've cloned the package with the intention of testing the server locally, but I'm running into issues.

First I `cd` to the image/scripts folder and made a config file:

```toml
[server]
http_port = 8080
http_ip = "127.0.0.1"
stop_file = "/tmp/stopregistrator"
log_level = "debug"

[github]
user = "BenJWard"
email = "benjward@protonmail.com"
name = "Ben J. Ward"
token = "<< a token I generated for my GH user >>"
secret = "<< the secret for the GH app I created >>"
app_id = 27978
priv_pem = "biojulia-registrar.2019-04-07.private-key.pem"

[targets.bio]
repo = "https://github.com/BioJulia/BioJuliaRegistry"
base_branch = "master"

[registrator]
trigger = "bioreg"
report_issue = false
issue_repo = "JuliaComputing/Registrator.jl"
reply_comment = true
set_status = true
enc_key = "<< a random string of numbers (len 16), I made >>"
disable_pull_request_trigger = false
disable_approval_process = false

[slack]
alert = false
token = "xxxx"
channel = "xxxx"
```

Next I started up the server locally: 

```julia
N82106:scripts bward$ julia run.jl conf.toml > >(tee -a stdout.log) 2> >(tee -a stderr.log >&2)
┌ Warning: Package Registrator does not have Logging in its dependencies:
│ - If you have Registrator checked out for development and have
│   added Logging as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Registrator
└ Loading Logging into Registrator from project dependency, future warnings for Registrator are suppressed.
┌ Info: Starting server...
└ @ Registrator.RegServer /Users/bward/.julia/packages/Registrator/JvPmZ/src/Server.jl:920
┌ Info: GitHub webhook starting...
│   trigger = r"@bioreg (.*?)$"
│   http_ip = 127.0.0.1
│   http_port = 8080
└ @ Registrator.RegServer /Users/bward/.julia/packages/Registrator/JvPmZ/src/Server.jl:907
```

Then, to expose my localhost to a url for the github app to use as a webhook, I used ngrok:

```
ngrok by @inconshreveable                                                           (Ctrl+C to quit)
                                                                                                    
Session Status                online                                                                
Account                       Ben J. Ward (Plan: Free)                                              
Version                       2.3.25                                                                
Region                        United States (us)                                                    
Web Interface                 http://127.0.0.1:4040                                                 
Forwarding                    http://9f2f77f4.ngrok.io -> http://localhost:8080                       
Forwarding                    https://9f2f77f4.ngrok.io -> http://localhost:8080                      
                                                                                                    
Connections                   ttl     opn     rt1     rt5     p50     p90                           
                              1       0       0.00    0.00    0.12    0.12                          
                                                                                                    
HTTP Requests                                                                                       
-------------                                                                    
```

Next I go to the github app and enter https://9f2f77f4.ngrok.io in the webhook url field and save. (Note I have not filled out a webhook secret, a setup URL, or a User authorization callback URL). Next, I install the app on BioJulia/FASTX.jl, open a new issue (https://github.com/BioJulia/FASTX.jl/issues/2), make a comment to activate the bot and... nothing. All I get is a notice in my ngrok window saying:

```
HTTP Requests                                                                                       
-------------                                                                                       
                                                                                                    
POST /                         400 Bad Request  
```

The GitHub app has permissions:

Read-Only: Repository Contents
Read + Write: Issues, Pull Requests, Commit Statuses

And it subscribes to Issue Comment and Commit Comment events.

The personal access token I use for the server has been given the `public_repo` scope (I wasnt sure if it needs others).

@nkottary Is there something I'm doing that is obviously wrong? Is there more I need to do before I can get this running locally? Once I get it working locally I can try and get it running on heroku. I'm happy to add you to BioJulia so as you can see the GitHub App settings and so on that I've created.
